streamer:
    #image: danisla/iot-streamer:x86.0.0.1
    build: ./x86
    command: bash
    environment:
        DEBUG:
        PORT: 8888
        PLAYER_DOCKER_IMAGE: "danisla/livestreamer:latest"
        RPI_PLAYER: "false"
        RESOLVE_URL: "false"
        IOT_ENDPOINT: "${IOT_ENDPOINT}"
        IOT_PORT: 8883
        THING_NAME: "${THING_NAME}"
    ports:
        - 8000:8000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
        - ./src/iot_streamer:/usr/src/app:ro
        - ./certs:/opt/certs:ro
