streamer:
    #image: danisla/iot-streamer:x86.0.0.1
    build: ./x86
    command: bash
    environment:
        DEBUG:
        PORT: 8888
        PLAYER_DOCKER_IMAGE: "danisla/livestreamer:latest"
        RPI_PLAYER: "false"
        RESOLVE_URL: "false"
        IOT_ENDPOINT: "${IOT_ENDPOINT}"
        IOT_PORT: 8883
        THING_NAME: raspberry-pi
        DOCKER_HOST:
        DOCKER_TLS_CA: "/docker/ca.pem"
        DOCKER_TLS_CERT: "/docker/cert.pem"
        DOCKER_TLS_KEY: "/docker/key.pem"

    # connect using VLC on dockerhost port 8000
    #net: host
    #user: nobody
    ports:
        - 8000:8000
    volumes:
        - ${DOCKER_CERT_PATH}:/docker:ro
        - ./iot-streamer.py:/opt/iot-streamer.py:ro
        - ./certs:/opt/certs:ro
